### PR TITLE
Add builds for 4.13, 4.14 and 5.0

### PR DESCRIPTION
**Pull request by tmcgilchrist**

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
@vbmithr any chance of getting this merged. The fixes for OCaml 5 would be super useful.

**Review by yawaramin — APPROVED** [review]

**Comment by yawaramin** [comment]
@tmcgilchrist if you are up for it maybe we could maintain a fork somewhere.

@vbmithr alternatively would you consider transferring maintainership over to us?

**Comment by tmcgilchrist** [comment]
Happy to help co-maintain something, and contribute fixes and some better docs.

**Comment by vthemelis** [comment]
FYI, @vbmithr has another OCaml library at least for the serialisation and deserialisation of Thrift. 

See: https://github.com/vbmithr/ocaml-thrift-lib/issues/4#issuecomment-1098185166

Might make sense to progressively move towards that although admittedly the RPC side is missing afaict.

**Comment by yawaramin** [comment]
@vthemelis that's cool, but as you said, it doesn't implement the RPC side of Thrift, and also it's using OCaml code as the 'source of truth', rather than the Thrift IDL file. The codegen is a pretty important aspect of Thrift, imho.

@tmcgilchrist I think the [ocaml-community](https://github.com/ocaml-community) GitHub org would be a nice place to host the fork. @c-cube can you advise us on setting up there? Or is there a good reason not to? Thx.

**Comment by vthemelis** [comment]
@vbmithr  is it possible to merge this? The build is green and it shouldn't need any extensive reviewing.

**Pull request merged**
